### ISSUE TITLE
更新到1.5.2工具无法正常打开

### ISSUE THREAD

**Issue by li-baige** [perlh/Wavely#11]
1.5.1可以正常按照步骤打开，但是今天更新到1.5.2之后，尝试无法打开。

已经尝试方法：
（1）https://support.apple.com/zh-cn/guide/mac-help/mh40616/15.0/mac/15.0
（2）sudo xattr -r -d com.apple.quarantine Wavely_darwin_arm64_1.5.2.app
（3）sudo codesign --sign - --force --deep Wavely_darwin_arm64_1.5.2.app

**Comment by li-baige** [comment]
ok，问题已经解决，解决方案：
执行如下命令即可：
chmod 755 /Users/$USER/Desktop/Wavely_darwin_arm64_1.5.2.app/Contents/MacOS/Wavely

**Comment by perlh** [comment]
好的，感谢你分享解决方案





------------------ 原始邮件 ------------------
发件人: 布布 ***@***.***&gt;
发送时间: 2024年12月5日 09:13
收件人: perlh/Wavely ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [perlh/Wavely] 更新到1.5.2工具无法正常打开 (Issue #11)





 
ok，问题已经解决，解决方案：
 执行如下命令即可：
 chmod 755 /Users/$USER/Desktop/Wavely_darwin_arm64_1.5.2.app/Contents/MacOS/Wavely
