### ISSUE TITLE
111

### ISSUE THREAD

**Issue by private-null** [perlh/Wavely#15]

**Comment by private-null** [comment]
sorry  1.5.1 可以打开

**Comment by private-null** [comment]
1.5.1 版本的

**Comment by perlh** [comment]
下周发布新版本





------------------ 原始邮件 ------------------
发件人: private null ***@***.***&gt;
发送时间: 2024年12月10日 11:07
收件人: perlh/Wavely ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [perlh/Wavely] mac intel 芯片无法打开 (Issue #15)





 
1.5.1 版本的
