### ISSUE TITLE
mac 的扫描任务为啥是纯白的

### ISSUE THREAD

**Issue by Miagz** [perlh/Wavely#17]
![December110948](https://github.com/user-attachments/assets/c7fd4ce4-6792-4a5b-9d0a-96691ae5d8f9)

**Comment by perlh** [comment]
你好，得先创建扫描任务





------------------ 原始邮件 ------------------
发件人: Miagz ***@***.***&gt;
发送时间: 2024年12月11日 09:49
收件人: perlh/Wavely ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [perlh/Wavely] mac 的扫描任务为啥是纯白的 (Issue #17)





 
December110948.png (view on web)
