### ISSUE TITLE
在windows环境下启动不了gui

### ISSUE THREAD

**Issue by zkj123** [perlh/Wavely#21]

**Comment by perlh** [comment]
稍后更新





------------------ 原始邮件 ------------------
发件人: zkj123 ***@***.***&gt;
发送时间: 2024年12月11日 13:41
收件人: perlh/Wavely ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [perlh/Wavely] 在windows环境下启动不了gui (Issue #21)

**Comment by perlh** [comment]
已发布新版本

**Comment by perlh** [comment]
已更新
