### ISSUE TITLE
不支持自定义接口吗？

### ISSUE THREAD

**Issue by N0o01** [perlh/Wavely#31]
<img width="582" alt="iShot_2024-12-19_00 04 55" src="https://github.com/user-attachments/assets/bce66b87-a986-4dde-a634-bf9d0bfd8b19" />
如图所示，我这样扫描默认去掉我输入的/api接口

**Comment by perlh** [comment]
目前不支持，下个版本将添加这个功能。

**Comment by perlh** [comment]
v2.0.0已支持api扫描
