### ISSUE TITLE
MAC版如何打开

### ISSUE THREAD

**Issue by wlaq-su** [perlh/Wavely#5]

**Comment by wlaq-su** [comment]
![image](https://github.com/user-attachments/assets/2d3459a6-ab07-4405-82ff-412cc80b5016)

**Comment by perlh** [comment]
https://support.apple.com/zh-tw/guide/mac-help/mh40616/14.0/mac/14.0

**Comment by wlaq-su** [comment]
还是不行，打不开

**Comment by perlh** [comment]
https://support.apple.com/zh-cn/guide/mac-help/mh40616/14.0/mac/14.0





------------------ 原始邮件 ------------------
发件人: wlaq-su ***@***.***&gt;
发送时间: 2024年11月28日 15:23
收件人: perlh/Wavely ***@***.***&gt;
抄送: Perlh ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [perlh/Wavely] MAC版如何打开 (Issue #5)





 
还是不行，打不开

**Comment by perlh** [comment]
你的mac是arm架构还是amd64的

**Comment by perlh** [comment]
可尝试这种方法：https://sspai.com/post/52828
